#change the port
server.port=8081
# PostgreSQL database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=julio108@
spring.datasource.driver-class-name=org.postgresql.Driver


# Optional: Hibernate (JPA) settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

